# Generated by Django 3.2 on 2022-08-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('mobileNumber', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
                ('assignedTime', models.CharField(max_length=200, null=True)),
                ('updationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100, null=True)),
                ('teamLeaderName', models.CharField(max_length=100, null=True)),
                ('teamMobno', models.CharField(max_length=20, null=True)),
                ('teamMembers', models.CharField(max_length=200, null=True)),
                ('postingDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
                ('firereport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firereport.firereport')),
            ],
        ),
        migrations.AddField(
            model_name='firereport',
            name='assignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firereport.team'),
        ),
    ]
